name: "Hola mundo"

on:
  push:
    branches:
      - main
jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
      - run: echo "pull"
      - run: echo "hacer otra cosa"
      - run: echo "tercera accion" 
